### ISSUE TITLE
Invalid video link on search results

### ISSUE THREAD

**Issue by hassaan-dev** [briskLimbs/briskLimbs#3]
Search is working but on search result video link is invalid

![search error](https://user-images.githubusercontent.com/34338953/54475250-0a8a7200-4811-11e9-896a-f301f2f5dbef.png)

**Comment by sakydev** [comment]
Fixed. 

For users who want to fix this without upgrading, please go to 

skins/ivar/skeleton/search.html

Now search "single-video-tabs.html" and replace it with "{{_coreUrl}}/watch/{{video.vkey}}"

Or see [this commit](https://github.com/briskLimbs/briskLimbs/commit/75250fb98fd9fa7ab7fdba097470d9ae9cef2431)

That's it!
