### ISSUE TITLE
Forgot Password not working

### ISSUE THREAD

**Issue by waqasaslamk** [briskLimbs/briskLimbs#48]
When I fill 'Username or Email' to reset my password it showed the message 'Please check your email for reset link' but still waiting for email.
here my username 'vicky' and email 'mwaqasaslam36@gmail.com'.

**Comment by sakydev** [comment]
Thank you @waqas-kang for creating this issue.

There were two problems

1. Email settings were incorrect
2. Forgot page wasn't determining username correctly.

Both of these issues have been fixed and you should start getting emails from now.
