### ISSUE TITLE
video uploading option 

### ISSUE THREAD

**Issue by waqasaslamk** [briskLimbs/briskLimbs#49]
1: When I browse a video for uploading and after selecting a video I realize that I selected a wrong video then there is no option to cancel video uploading.
2: After uploading video it should redirect to video manager/list page.

**Comment by sakydev** [comment]
Hi @waqas-kang,

1. This is planned for next releases. For now you can simply refresh page and upload will be cancelled
2. This is not done on purpose. We want to allow user to make any changes to title or description as they like for as many times as needed without having to go to video editor. If they have to make changes to other fields then they can simply browse to videos manger
